apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard
  labels:
    app: admin-dashboard
    tier: fronend
  namespace: dev-env
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: admin-dashboard

  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
     containers:
      - name: admin-dashboard
        image: "209992271656.dkr.ecr.eu-west-1.amazonaws.com/vozze-admin-dashboard"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-svc
  namespace: dev-env
  labels:
    app: admin-dashboard
spec:
  type: NodePort
  selector:
    app: admin-dashboard
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-dashboard
  namespace: dev-env
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/conditions.admin-dashboard-svc: |
      [{"field":"host-header","hostHeaderConfig":{"values":["admin-dashboard.vozze.com.ng"]}}]
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:821511923493:certificate/6cc1c5a0-9f4d-42ef-a99f-036702d01f96
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: mojec-group
    alb.ingress.kubernetes.io/ssl-redirect: '443' 
    
spec:
  rules:
    - host: "admin-dashboard.vozze.com.ng"
    - http: 
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name:  admin-dashboard-svc
              port:
                number: 3000