apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-dashboard
  labels:
    app: admin-dashboard
    tier: fronend
  namespace: dev-env
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: admin-dashboard

  template:
    metadata:
      labels:
        app: admin-dashboard
    spec:
     containers:
      - name: admin-dashboard
        image: "209992271656.dkr.ecr.eu-west-1.amazonaws.com/vozze-admin-dashboard"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: admin-dashboard-svc
  namespace: dev-env
  labels:
    app: admin-dashboard
spec:
  type: NodePort
  selector:
    app: admin-dashboard
  ports:
    - port: 3000
      targetPort: 3000