name: Build Docker image and push to repo.
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build, tag, and push image to Amazon ECR
        uses: actions/checkout@v2
      - env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
           ECR_REPOSITORY: vozze-admin-dashboard
           IMAGE_TAG1: ${{ github.sha }}
           IMAGE_TAG2: latest
        run: |
           docker build . --file Dockerfile --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1 --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG1
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG2
           
      - name: Deploy to cluster
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.6'
          id: installer
      - env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: vozze-admin-dashboard
          IMAGE_TAG: latest #${{ github.sha }}
        run: |
           aws eks update-kubeconfig --name vozze-cluster --region aws-region: eu-west-2
           kubectl apply -f K8s/dev/deployment.yaml
           
          # restart service
      - run: | 
           kubectl -n dev-env rollout restart deployment admin-dashboard
